version: 2.1

# Reuse a common job for publishing each orb

# Orbs follow the conventions:
#   Directory named the same as the orb
#   A single docker image in the executor directory
#   The orb yaml is in a file name orb.yml
#   Published in the ovotech namespace

jobs:
  publish_orb:
    description: Publish an orb
    parameters:
      path:
        type: string
        description: The path to the orb
    docker:
    - image: 361339499037.dkr.ecr.eu-west-1.amazonaws.com/pe-orbs:latest
    steps:
    - checkout
    - setup_remote_docker:
        version: 17.11.0-ce
    - run:
        name: docker build << parameters.path >>
        command: |
          set -e

          docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD

          readonly ORB="<< parameters.path >>"

          for path in $ORB/executor/Dockerfile*; do

              filename=$(basename $path)

              if [[ "$filename" == "Dockerfile" ]]; then
                  TAG="latest"
                  BUILD_TAG="$(date "+%d-%m-%Y")"
              else
                  TAG="${filename#"Dockerfile-"}"
                  BUILD_TAG="${terraform}$(date "+%d-%m-%Y")"
              fi

              docker build --tag "ovotech/${ORB}:${BUILD_TAG}" \
              --label org.label-schema.vcs-ref="$CIRCLE_SHA1" \
              --label org.label-schema.vcs-url="$CIRCLE_REPOSITORY_URL" \
              --label org.label-schema.schema-version="1.0" \
              --file $path \
              "${ORB}/executor"

              docker push "ovotech/${ORB}:${BUILD_TAG}"

              DIGEST=$(docker image inspect --format="{{index .RepoDigests 0}}" "ovotech/${ORB}:${BUILD_TAG}")
              echo $DIGEST > "${ORB}_${TAG}_digest.txt"

              if [ "$CIRCLE_BRANCH" = "master" ]; then
                  docker tag "ovotech/${ORB}:${BUILD_TAG}" "ovotech/${ORB}:${TAG}"
                  docker push "ovotech/${ORB}:${TAG}"
              fi
          done

    - run:
        name: Publish << parameters.path >> orb
        command: |
          set -e

          readonly ORB="<< parameters.path >>"

          tools/include.py "${ORB}/orb.yml" > "/tmp/${ORB}_orb.yml"

          for path in $ORB/executor/Dockerfile*; do

              filename=$(basename $path)

              if [[ "$filename" == "Dockerfile" ]]; then
                  TAG="latest"
              else
                  TAG="${filename#"Dockerfile-"}"
              fi

              DIGEST=$(<"${ORB}_${TAG}_digest.txt")
              sed -i -e "s|ovotech/${ORB}:$TAG|$DIGEST|" "/tmp/${ORB}_orb.yml"
          done

          circleci orb publish "/tmp/${ORB}_orb.yml" "ovotech/${ORB}@dev:$CIRCLE_BRANCH" --token "$CIRCLECI_TOKEN"

          if [ "$CIRCLE_BRANCH" = "master" ]; then
              circleci orb source "ovotech/${ORB}" > "/tmp/${ORB}_current.yml"

              if ! cmp -s "/tmp/${ORB}_orb.yml" "/tmp/${ORB}_current.yml"; then
                  circleci orb publish increment "/tmp/${ORB}_orb.yml" "ovotech/${ORB}" patch --token "$CIRCLECI_PROD_TOKEN"
              fi
          fi

workflows:
  commit:
    jobs:
    - publish_orb:
        name: clair-scanner
        path: clair-scanner
    - publish_orb:
        name: terraform
        path: terraform
